# Config nodes:
#
# auto-reloadconfig(int): <Time in minutes to check/reload config for message updates(0 for off)>
#     NOTE: When config is reloaded, will reset delays for messages and cause one-time messages to resend
# debug-mode(boolean): <Should we print debug to server.log(true/false)?>
#     NOTE: Look for fine and finer level log messages in server.log
# announcements: Add announcements below to this section
#     <message label>(String, must be unique):
#         message(String, required) OR messages(String list, see sample config): <Message to send>
#         random-order(boolean, optional): <if list of messages should be sent in random order>
#         sender(String, optional): <Message Sender(chat or boss, default: chat)>
#         bar(section, optional):
#             hold(int, optional): <Time in sections for bar to be displayed on announce>
#             color(String, optional): <bar color(https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html)>
#             style(String, optional): <bar style(https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html)>
#             animate(section, optional):
#                 enable(boolean, optional): <if bar should animate hold time>
#                 reverse(boolean, optional): <if animation should be reversed>
#         delay(int, optional - default 0): <Delay to send message on in seconds>
#         repeat(int, optional): <time between repeat sendings of the message in seconds>
#         includesperms(String list, optional):
#         - <only send to those with this perm>
#         - <and this one>
#         excludesperms(String list, optional):
#         - <don't send to those with this perm>
#         - <and this one>
#
# -------------------------
#
#  Note: For permissions, includes are applied first, then excludes are taken out

autoReload: 10m
debugMode: false
announcements:
  - type: Chat
    delay: 30s
    repeat: 2m
    includesPermissions:
      - permissions.build
      - another.permission
    excludesPermissions:
      - permissions.admin
    messages:
      - hello
      - world
  - type: Chat
    repeat: 1m 40s
    messages:
      - abc
      - xyz
  - type: Title
    repeat: 30s
    messages:
      - title: Title!
        subtitle: Subtitle!
      - title: Title only custom durations
        fadeIn: 100ms
        stay: 10s
        fadeOut: 1s
    fadeIn: 500ms
    stay: 5s
    fadeOut: 500ms
  - type: Boss
    random: true
    repeat: 15s
    messages:
      - message: eyy
      - message: custom bar config
        hold: 10s
        color: GREEN
        style: SEGMENTED_20
        reverseAnimation: true
    hold: 5s
    color: PURPLE
    style: SOLID
    animate: true
config-version: 1
