name: SimpleAnnounce
main: org.simplemc.simpleannounce.SimpleAnnounce
version: 1.0.0
api-version: "1.15"
website: https://github.com/SimpleMC/SimpleAnnounce
author: tajobe
permissions:
    simpleannounce.reload:
        description: Allow reloading SimpleAnnounce config
        children:
            simpleannounce: true
commands:
    simpleannouncereload:
        description: SimpleAnnounce command for help or config reload
        aliases:
            - sareload
            - sar
        usage: |
            /<command> | Reloads SimpleAnnounce config
