name: SimpleAnnounce
main: org.simplemc.simpleannounce.SimpleAnnounce
version: 1.9.3
website: http://SimpleMC.org/simpleannounce/
author: Taylor Becker
permissions:
    simpleannounce:
        description: Gives access to SimpleAnnounce help command
    simpleannounce.reload:
        description: Gives access to SimpleAnnounce reload command
        children:
            simpleannounce: true
commands:
    simpleannounce:
        description: SimpleAnnounce command for help or config reload
        usage: |
            /<command> | Displays SimpleAnnounce help
            /<command> r | Reloads SimpleAnnounce config
            /<command> reload | Reloads SimpleAnnounce config
